
networks:
  vote:
    driver: bridge

services:
  vote:
    image: rodrigoaro/vote:v1
    build:
      context: ./vote
      dockerfile: Dockerfile
    ports:
      - 80
    depends_on:
      - redis
    networks:
      - vote

  
  worker:
    image: rodrigoaro/worker:v1
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - redis
      - db
    networks:
      - vote

  
  result:
    image: rodrigoaro/result:v1
    build:
      context: ./result
      dockerfile: Dockerfile
    environment:
      - PORT=80
    ports:
      - 80
    depends_on:
      - db
    networks:
      - vote



  redis:
    image: redis:6.0-alpine
    networks:
      - vote


  db:
    image: postgres:12-alpine
    networks:
      - vote
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust





